name: "textlint-ghaction"
author: "c6h4clch3"
description: |
  textlint excutor on GitHub Actions
inputs:
  target:
    description: |
      Target files to lint
    required: false
    default: ./*.txt
  config_file:
    description: |
      Locates textlintrc.* file
    required: false
    default: ""
outputs:
  result_logs:
    description: |
      the result logs of textlint.

runs:
  using: "docker"
  image: "Dockerfile"
