name: "textlint-ghaction"
author: "c6h4clch3"
description: |
  textlint excutor on GitHub Actions
inputs:
  target:
    description: |
      Target files to lint
    required: false
    default: ./*.txt
  config_file:
    description: |
      Locates textlintrc.* file
    required: false
    default: ""
  use_reviewdog:
    description: |
      if "true", the result will be notified with reviewdog.
      It is Also needed input.github_token set to use.
    required: false
    default: ""
  github_token:
    description: |
      GitHub API tokens, used to notify the result with reviewdog.
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
