name: "textlint-ghaction"
author: "c6h4clch3"
description: |
  textlint excutor on GitHub Actions
inputs:
  workdir:
    description: |
      Working directory of textlint
    required: false
    default: ./*.txt
  configFile:
    description: |
      Locates textlintrc.* file
    required: false
    default: ""
  silent:
    description: |
      If true, set the exit code always 0 even though on error,
      and the result logs and exit code are passed to outputs.
    required: false
    default: "false"
outputs:
  result_logs:
    description: |
      the result logs of textlint,
      set when INPUTS_SILENT is true.
  exit_code:
    description: |
      the exit code of textlint,
      set when INPUTS_SILENT is true.

runs:
  using: "docker"
  image: "Dockerfile"
