name: "textlint-ghaction"
author: "c6h4clch3"
description: |
  textlint excutor on GitHub Actions
inputs:
  workdir:
    description: |
      Working directory of textlint
    required: false
    default: ./*.txt
  configFile:
    description: |
      Locates textlintrc.* file
    required: false
    default: ""
outputs:
  textlint_result:
    description: |
      the result message of textlint
runs:
  using: "docker"
  image: "Dockerfile"
