name: "textlint-ghaction"
author: "c6h4clch3"
description: |
  textlint excutor on GitHub Actions
inputs:
  workdir:
    description: |
      Working directory of textlint
    required: false
    default: ./*.txt
runs:
  using: "docker"
  image: "Dockerfile"
