name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: textlint
      - run: "echo ${{ steps.textlint.outputs.textlint_result }}"
